### ISSUE TITLE
Fix chest sliders in tough gui

### ISSUE THREAD

**Issue by AmeyaWagh** [WPI-Humanoid-Robotics-Lab/tough#17]
Two sliders are changing the same thing.

**Comment by ninja777** [comment]
Commit: 11ded335dab69a2becf428b8ffcc0ca9710d236d should fix this. @AshayAswale can you test and close this issue?

**Comment by AshayAswale** [comment]
All three sliders are working fine and independently. But on clicking 'Reset Chest', the sliders are set to some intermediate value, and not the end value. This is because when the `getChestState()` is called, the robot is still in motion, and continues to move after the slider values are set. Should I raise a different issue for this? because the same thing is happening with 'Reset Arm'. But this is not a critical issue.

**Comment by ninja777** [comment]
The reset button issue is due to addition of gripper tab. Let's keep this issue open until the next UI commit is merged. I'll fix it in that commit.

**Comment by AshayAswale** [comment]
All sliders working fine, `wrist pitch slider` fixed in commit https://github.com/WPI-Humanoid-Robotics-Lab/tough/commit/dc27b6e262ba530f3285c26d4f2582d4581e46d8
