### ISSUE TITLE
MultisenseImage disparity subscriber has wrong message type

### ISSUE THREAD

**Issue by dpwivagg** [WPI-Humanoid-Robotics-Lab/tough#24]
When calling `giveDisparityImage(disp)` as in test_organizedRGBD.cpp, the error below occurs. It is clear in MultisenseImage.cpp that `loadDisparityImageStereoMsgs()` should be used for getting disparity in the simulation, but there is no way to toggle this callback instead of the default, `loadDisparityImageSensorMsgs()`. Simply swapping out the callback causes a build error.

```
[ERROR] [1555269995.461649677, 1419.920000000]: Client [/atlas_object_sorting_perception] wants topic /multisense/camera/disparity to have datatype/md5sum [sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743], but our version has [stereo_msgs/DisparityImage/04a177815f75271039fa21f16acad8c9]. Dropping connection.
```

**Comment by ninja777** [comment]
This is fixed in rbe-595 branch which is used for the humanoid robotics course. Gazebo uses different type of messages, hence the error. 

Note: all the methods with give* names are replaced by get* names. please modify your code accordingly. The test example [here](https://github.com/WPI-Humanoid-Robotics-Lab/tough/blob/rbe-595/tough_examples/src/perception_examples/test_multisense_image.cpp) can be referred for usage with gazebo.
